"""How deepctl v0.3.2 wrote its skill files, quoted so tests can regenerate them.

Quoted from tag v0.3.2, packages/deepctl-core/src/deepctl_core/skill_generator.py:
- l.711-719 ``SkillGenerator._write_repo_skills`` (the base class, which Cursor,
  Cline, Amazon Q and Aider inherit): the joined file.
- l.796-797 ``CodexGenerator._BEGIN`` / ``_END``.
- l.815-832 ``CodexGenerator._merge`` and ``_write_repo_skills``: the section in
  Codex's file; Gemini and OpenCode copy them byte for byte.
Only ``self`` and the file I/O are replaced by parameters and return values.
The skills dict is ordered api, docs, setup-mcp, starters (``skill_names``, l.87).
v0.3.2 used ``path.read_text()``/``write_text()``: universal newlines on read, and
"\\n" written as-is on POSIX.
"""

_BEGIN = "<!-- BEGIN deepctl CLI Reference (auto-generated by deepctl) -->"
_END = "<!-- END deepctl CLI Reference -->"


def joined(repo_skills: dict[str, str]) -> str:
    # l.713
    combined = "\n\n---\n\n".join(repo_skills.values())
    return combined


def _merge(existing: str | None, section: str) -> str:
    # l.815-825, with ``path.exists()`` / ``path.read_text()`` as ``existing``.
    if existing is None:
        return section
    if _BEGIN in existing:
        before = existing[: existing.index(_BEGIN)]
        after_end = existing.find(_END)
        after = existing[after_end + len(_END) :] if after_end != -1 else ""
        return before + section + after.lstrip("\n")
    return existing.rstrip("\n") + "\n\n" + section


def shared(repo_skills: dict[str, str], existing: str | None) -> str:
    # l.827-832
    combined = "\n\n---\n\n".join(repo_skills.values())
    wrapped = f"{_BEGIN}\n{combined}\n{_END}\n"
    return _merge(existing, wrapped)
