[build]
  base    = "web"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  SITE_URL     = "https://cli.deepgram.com"

[context.staging]
  [context.staging.environment]
    SITE_URL = "https://staging--deepgram-cli-web.netlify.app"
